#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

define('ROOT_PATH', __DIR__);

use Symfony\Component\Console\Application;

$app = new Application('Swoole demo', 'v0.1');

$app->add(new \App\Commands\HttpServerCommand());

$res = $app->run();
exit($res);
//
//$host = '0.0.0.0';
//$port = 9501;
//
//$server = new Server($host, $port);
//
//$server->on('request', function (Request $request, Response $response) use ($app) {
////    var_dump($request->cookie);
//
//    $app->handleSwooleRequest($request, $response);
//});
//
//echo "Http server listening on http://$host:$port , you can open url http://127.0.0.1:$port in browser.\n";
//
//$server->start();
